name: CI

on:
  issue_comment:
    types: [created]

jobs:
  if: ${{ !github.event.issue.pull_request }} && ( github.actor == 'lleadbet' || github.actor == 'jbulava' )
  label_issue:
    # if an issue AND either Jon or Lucas comment
    runs-on: ubuntu-latest

    steps:
      - name: DebugEcho
        run: echo "Body ${{ github.event.issue.body }}"
      - name: Label as Ticketed
        uses: actions/github-script@v3
        # if not ticketed already and the text contains "Ticketed"
        if: ${{ contains(github.event.issue.body, 'Ticketed') }} 
        with:
          debug: true
          script: |
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['ticketed']
            })


