name: CI

on:
  issue_comment:
    types: [created]

jobs:
  label_issue:
    # if an issue AND either Jon or Lucas comment
    if: ${{ !github.event.issue.pull_request && ( github.actor == 'lleadbet' || github.actor == 'jbulava' ) }}
    runs-on: ubuntu-latest

    steps:
      - name: DebugEcho
        env:
          GITHUB_CONTEXT: ${{ toJSON(github.event.issue) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Label as Ticketed
        uses: actions/github-script@v3
        # if not ticketed already and the text contains "Ticketed"
        if: ${{ !contains(github.event.issue.labels.*.name, 'ticketed') && contains(github.event.issue.body, 'Ticketed') }} 
        with:
          debug: true
          script: |
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['ticketed']
            })


