name: Issue Automation

on:
  issue_comment:
    types: [created]

jobs:
  label_issue:
    # if an issue AND either Jon or Lucas comment then continue- otherwise it's not triggered. 
    if: ${{ !github.event.issue.pull_request && ( github.actor == 'lleadbet' || github.actor == 'jbulava' ) }}
    runs-on: ubuntu-latest

    steps:
      - name: Mark as Done
        uses: actions/github-script@v3
        # if ticketed and the body contains either "closing" or "fixed", mark as done. 
        if: ${{ contains(github.event.issue.labels.*.name, 'ticketed') && ( contains(github.event.comment.body, 'Closing') || contains(github.event.comment.body, 'Fixed') ) }} 
        with:
          script: |
           github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['done']
            })
      - name: Label as Ticketed
        uses: actions/github-script@v3
        # if not ticketed already and the text contains "Ticketed"
        if: ${{ !contains(github.event.issue.labels.*.name, 'ticketed') && contains(github.event.comment.body, 'Ticketed') }} 
        with:
          script: |
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['ticketed']
            })         

